api = "0.7"

[buildpack]
  description = "A buildpack for configurating FPM"
  homepage = "https://github.com/paketo-buildpacks/php-fpm"
  id = "paketo-buildpacks/php-fpm"
  keywords = ["php", "fpm"]
  name = "Paketo Php FPM Buildpack"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php-fpm/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "config/php-fpm-base.conf", "config/php-fpm-buildpack.conf"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
